# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproject.proto\x12\x07project\"D\n\x14\x43reateProjectRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"E\n\x10\x43reateTagRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t\"8\n\x11GetProjectRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\"O\n\x0fProjectResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\"\n\x04tags\x18\x03 \x03(\x0b\x32\x14.project.TagResponse\";\n\x0bTagResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t2\xd8\x01\n\nProjectSvc\x12H\n\rcreateProject\x12\x1d.project.CreateProjectRequest\x1a\x18.project.ProjectResponse\x12<\n\tcreateTag\x12\x19.project.CreateTagRequest\x1a\x14.project.TagResponse\x12\x42\n\ngetProject\x12\x1a.project.GetProjectRequest\x1a\x18.project.ProjectResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEPROJECTREQUEST._serialized_start=26
  _CREATEPROJECTREQUEST._serialized_end=94
  _CREATETAGREQUEST._serialized_start=96
  _CREATETAGREQUEST._serialized_end=165
  _GETPROJECTREQUEST._serialized_start=167
  _GETPROJECTREQUEST._serialized_end=223
  _PROJECTRESPONSE._serialized_start=225
  _PROJECTRESPONSE._serialized_end=304
  _TAGRESPONSE._serialized_start=306
  _TAGRESPONSE._serialized_end=365
  _PROJECTSVC._serialized_start=368
  _PROJECTSVC._serialized_end=584
# @@protoc_insertion_point(module_scope)
