# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x1e\n\rVerifyRequest\x12\r\n\x05token\x18\x01 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"@\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"F\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\"9\n\x0eVerifyResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"3\n\x16\x43hangeUserEmailRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t2\xa8\x02\n\x0bUserService\x12\x35\n\x08register\x12\x15.user.RegisterRequest\x1a\x12.user.UserResponse\x12/\n\x05login\x12\x12.user.LoginRequest\x1a\x12.user.UserResponse\x12\x33\n\x06verify\x12\x13.user.VerifyRequest\x1a\x14.user.VerifyResponse\x12\x35\n\x07getUser\x12\x14.user.GetUserRequest\x1a\x14.user.VerifyResponse\x12\x45\n\x0f\x63hangeUserEmail\x12\x1c.user.ChangeUserEmailRequest\x1a\x14.user.VerifyResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VERIFYREQUEST._serialized_start=20
  _VERIFYREQUEST._serialized_end=50
  _GETUSERREQUEST._serialized_start=52
  _GETUSERREQUEST._serialized_end=85
  _LOGINREQUEST._serialized_start=87
  _LOGINREQUEST._serialized_end=134
  _REGISTERREQUEST._serialized_start=136
  _REGISTERREQUEST._serialized_end=200
  _USERRESPONSE._serialized_start=202
  _USERRESPONSE._serialized_end=272
  _VERIFYRESPONSE._serialized_start=274
  _VERIFYRESPONSE._serialized_end=331
  _CHANGEUSEREMAILREQUEST._serialized_start=333
  _CHANGEUSEREMAILREQUEST._serialized_end=384
  _USERSERVICE._serialized_start=387
  _USERSERVICE._serialized_end=683
# @@protoc_insertion_point(module_scope)
